---
- name: 'Play to install Sublime Text Editor'
  hosts: 'all'
  gather_facts: true
  connection: 'local'
    config_dir: '{{ ansible_env.HOME}}/.config/sublime-text'
  roles:
      - role: 'chaosmail.sublime-text'
        vars:
          sublime_version: 4
          sublime_package_control: false
  tasks:
      - name: 'Create Package control directory'
        file:
          path: '{{ config_dir }}/Installed Packages'
          state: 'directory'
          owner: '{{ ansible_env.USER }}'
          group: '{{ ansible_env.USER }}'
          mode: 0770

      - name: 'Copy Package control'
        copy:
          src: '{{ playbook_dir }}/files/Package Control.sublime-package'
          dest: '{{ config_dir }}/Installed Packages/'
          owner: '{{ ansible_env.USER }}'
          group: '{{ ansible_env.USER }}'
          mode: 0664

      - name: 'Copy Package control settings'
        copy:
          src: '{{ playbook_dir }}/files/{{ ansible_system | lower }}/{{ item }}'
          dest: '{{ config_dir}}/Packages/User/'
          owner: '{{ ansible_env.USER }}'
          group: '{{ ansible_env.USER }}'
          mode: 0664
        loop:
          - 'Package Control.sublime-settings'
          - 'Anaconda.sublime-settings'

      - name: 'Launch sublime-text editor - Plugin provisioning'
        shell: 'subl && subl --version'
        args:
          executable: '/bin/bash'
        changed_when: false
        register: 'subl_version'

      - name: 'Display sublime-text editor version'
        debug:
          var: 'subl_version.stdout'
...
