---

- name: 'Play to install Sublime Text Editor'
  hosts: 'all'
  become: true
  gather_facts: true
  connection: 'local'
  roles:
      - role: 'chaosmail.sublime-text'
        vars:
          sublime_version: 4
          sublime_package_control: true
...
